language: ruby
bundler_args: --without production --path=~/.bundle
rvm:
  - 2.1.2
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate db:schema:load
script: 'rspec'
env:
  global:
  - RAILS_ENV=test